### ISSUE TITLE
exception with "list_metwork_processes.py"

### ISSUE THREAD

**Issue by thefab** [metwork-framework/mfcom#112]
full logs:

```
2019-03-27T09:57:11.432Z  [WARNING] : (telegraf_collector_metwork_module#26483) can't execute list_metwork_processes.py --output-format=json --include-current-family: 
===== BASH COMMAND =======================
list_metwork_processes.py --output-format=json --include-current-family
===== BASH RETURN CODE ===================
1
===== BASH STDERR ========================
Traceback (most recent call last):
  File "/opt/metwork-mfext-0.5/opt/python3/lib/python3.5/site-packages/psutil/_pslinux.py", line 1402, in wrapper
    return fun(self, *args, **kwargs)
  File "/opt/metwork-mfext-0.5/opt/python3/lib/python3.5/site-packages/psutil/_pslinux.py", line 1978, in uids
    data = self._read_status_file()
  File "/opt/metwork-mfext-0.5/opt/python3/lib/python3.5/site-packages/psutil/_common.py", line 337, in wrapper
    return fun(self)
  File "/opt/metwork-mfext-0.5/opt/python3/lib/python3.5/site-packages/psutil/_pslinux.py", line 1457, in _read_status_file
    with open_binary("%s/%s/status" % (self._procfs_path, self.pid)) as f:
  File "/opt/metwork-mfext-0.5/opt/python3/lib/python3.5/site-packages/psutil/_pslinux.py", line 187, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/27740/status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/metwork-mfcom-0.5/bin/list_metwork_processes.py", line 103, in <module>
    processes = get_processes(exclude_same_family=None)
  File "/opt/metwork-mfcom-0.5/bin/list_metwork_processes.py", line 49, in get_processes
    if proc.username() != USER:
  File "/opt/metwork-mfext-0.5/opt/python3/lib/python3.5/site-packages/psutil/__init__.py", line 683, in username
    real_uid = self.uids().real
  File "/opt/metwork-mfext-0.5/opt/python3/lib/python3.5/site-packages/psutil/_common.py", line 337, in wrapper
    return fun(self)
  File "/opt/metwork-mfext-0.5/opt/python3/lib/python3.5/site-packages/psutil/__init__.py", line 721, in uids
    return self._proc.uids()
  File "/opt/metwork-mfext-0.5/opt/python3/lib/python3.5/site-packages/psutil/_pslinux.py", line 1413, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=27740)
```

**Comment by thefab** [comment]
already fixed in master with #108 , let's backport in 0.5 with #113
